agrega verificacion de config

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -17,11 +17,17 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           ref: exp
 
-          
+      - name: Verify config.yaml
+        run: |
+          if [ ! -f $GITHUB_WORKSPACE/src/dags/config.yml ]; then
+            echo "config.yml not found!"
+            exit 1
+          fi
+
       - name: Setup Python 3.11
         uses: actions/setup-python@v4
         with:
